name: Build and Push Docker Images

on:
  workflow_dispatch:

jobs:
  build-and-push-auth-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push auth-service
        uses: docker/build-push-action@v4
        with:
          context: ./services/auth-service
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-service:latest

  build-and-push-auth-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push auth-database
        uses: docker/build-push-action@v4
        with:
          context: ./database/auth-database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/auth-database:latest
